import { Appointment } from '@/types';

export const appointments: Appointment[] = [
  // Hoy - 25 de Agosto 2025
  {
    id: '1',
    clienteNombre: 'Juan',
    clienteApellidos: 'Pérez García',
    telefono: '+34 658 123 456',
    servicio: 'Corte de cabello adulto',
    variante: 'Degradado lateral',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-25',
    horaInicio: '10:00',
    descuentos: ['Promo verano', 'Cliente VIP'],
  },
  {
    id: '2',
    clienteNombre: 'María',
    clienteApellidos: 'López Fernández',
    telefono: '+34 697 854 321',
    servicio: 'Afeitado clásico',
    variante: 'Con toalla caliente',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-08-25',
    horaInicio: '11:00',
    descuentos: ['Descuento familia'],
  },
  {
    id: '3',
    clienteNombre: 'Diego',
    clienteApellidos: 'Sánchez Ruiz',
    telefono: '+34 612 987 654',
    servicio: 'Corte + Barba',
    variante: 'Estilo moderno',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-25',
    horaInicio: '12:30',
    descuentos: ['Pack completo'],
  },
  {
    id: '4',
    clienteNombre: 'Alex',
    clienteApellidos: 'González Torres',
    telefono: '+34 634 567 890',
    servicio: 'Corte infantil',
    variante: 'Primera vez',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-08-25',
    horaInicio: '14:00',
    descuentos: ['Promo niños'],
  },
  {
    id: '5',
    clienteNombre: 'Roberto',
    clienteApellidos: 'Morales Vila',
    telefono: '+34 645 234 567',
    servicio: 'Tratamiento capilar',
    variante: 'Anti-caspa',
    sucursal: 'Parets',
    profesional: 'Sara López',
    fechaISO: '2025-08-25',
    horaInicio: '15:30',
  },
  {
    id: '6',
    clienteNombre: 'Fernando',
    clienteApellidos: 'Castro Vega',
    telefono: '+34 623 456 789',
    servicio: 'Arreglo de barba',
    variante: 'Perfilado completo',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-08-25',
    horaInicio: '16:00',
    descuentos: ['Cliente frecuente'],
  },
  {
    id: '7',
    clienteNombre: 'Carlos',
    clienteApellidos: 'Mendoza Silva',
    telefono: '+34 678 901 234',
    servicio: 'Corte de cabello adulto',
    variante: 'Con líneas',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-25',
    horaInicio: '09:00',
    descuentos: ['Primera visita'],
    noShow: true,
  },

  // Mañana - 26 de Agosto 2025
  {
    id: '8',
    clienteNombre: 'Patricia',
    clienteApellidos: 'Ruiz Martín',
    telefono: '+34 667 890 123',
    servicio: 'Lavado + Peinado',
    variante: 'Para evento',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-08-26',
    horaInicio: '10:30',
    descuentos: ['Oferta especial'],
  },
  {
    id: '9',
    clienteNombre: 'Antonio',
    clienteApellidos: 'García López',
    telefono: '+34 689 012 345',
    servicio: 'Corte clásico',
    variante: 'Tijera únicamente',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-26',
    horaInicio: '11:00',
  },
  {
    id: '10',
    clienteNombre: 'Sofia',
    clienteApellidos: 'Herrera Díaz',
    telefono: '+34 690 123 456',
    servicio: 'Afeitado clásico',
    variante: 'Con aceites esenciales',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-08-26',
    horaInicio: '14:00',
  },
  {
    id: '11',
    clienteNombre: 'Miguel',
    clienteApellidos: 'Torres Vega',
    telefono: '+34 701 234 567',
    servicio: 'Corte + Barba',
    variante: 'Estilo clásico',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-26',
    horaInicio: '16:30',
    descuentos: ['Pack completo'],
  },

  // Pasado mañana - 27 de Agosto 2025
  {
    id: '12',
    clienteNombre: 'Raquel',
    clienteApellidos: 'Jiménez Silva',
    telefono: '+34 712 345 678',
    servicio: 'Tratamiento capilar',
    variante: 'Hidratación profunda',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-08-27',
    horaInicio: '09:30',
  },
  {
    id: '13',
    clienteNombre: 'Eduardo',
    clienteApellidos: 'Moreno Castro',
    telefono: '+34 723 456 789',
    servicio: 'Corte infantil',
    variante: 'Degradado suave',
    sucursal: 'Parets',
    profesional: 'Sara López',
    fechaISO: '2025-08-27',
    horaInicio: '11:00',
    descuentos: ['Promo niños'],
  },
  {
    id: '14',
    clienteNombre: 'Carmen',
    clienteApellidos: 'Blanco Ruiz',
    telefono: '+34 734 567 890',
    servicio: 'Arreglo de barba',
    variante: 'Estilo hipster',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-08-27',
    horaInicio: '15:00',
  },

  // Ayer - 24 de Agosto 2025
  {
    id: '15',
    clienteNombre: 'Javier',
    clienteApellidos: 'Delgado Ortiz',
    telefono: '+34 745 678 901',
    servicio: 'Corte clásico',
    variante: 'Estilo ejecutivo',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-24',
    horaInicio: '10:00',
  },
  {
    id: '16',
    clienteNombre: 'Lucia',
    clienteApellidos: 'Navarro Pérez',
    telefono: '+34 756 789 012',
    servicio: 'Lavado + Peinado',
    variante: 'Estilo casual',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-08-24',
    horaInicio: '12:30',
    descuentos: ['Cliente VIP'],
  },
  {
    id: '17',
    clienteNombre: 'Pablo',
    clienteApellidos: 'Ramos García',
    telefono: '+34 767 890 123',
    servicio: 'Corte + Barba',
    variante: 'Estilo moderno',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-08-24',
    horaInicio: '16:00',
    noShow: true,
  },

  // Próxima semana - 28 de Agosto 2025
  {
    id: '18',
    clienteNombre: 'Ana',
    clienteApellidos: 'Vázquez Torres',
    telefono: '+34 778 901 234',
    servicio: 'Tratamiento capilar',
    variante: 'Reparación intensiva',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-08-28',
    horaInicio: '10:00',
  },
  {
    id: '19',
    clienteNombre: 'Ricardo',
    clienteApellidos: 'Molina Fernández',
    telefono: '+34 789 012 345',
    servicio: 'Afeitado clásico',
    variante: 'Tradicional',
    sucursal: 'Parets',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-08-28',
    horaInicio: '14:30',
    descuentos: ['Cliente frecuente'],
  },
  {
    id: '20',
    clienteNombre: 'Isabel',
    clienteApellidos: 'Serrano Vila',
    telefono: '+34 790 123 456',
    servicio: 'Corte de cabello adulto',
    variante: 'Estilo bob',
    sucursal: 'Lliçà',
    profesional: 'Sara López',
    fechaISO: '2025-08-28',
    horaInicio: '17:00',
  },
];
