import { Appointment } from '@/types';

export const appointments: Appointment[] = [
  {
    id: '1',
    clienteNombre: 'Juan',
    clienteApellidos: 'Pérez García',
    telefono: '+34 658 123 456',
    servicio: 'Corte de cabello adulto',
    variante: 'Degradado lateral',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-01-23',
    horaInicio: '10:00',
    descuentos: ['Promo verano', 'Cliente VIP'],
  },
  {
    id: '2',
    clienteNombre: 'María',
    clienteApellidos: 'López Fernández',
    telefono: '+34 697 854 321',
    servicio: 'Afeitado clásico',
    variante: 'Con toalla caliente',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-01-23',
    horaInicio: '11:00',
    descuentos: ['Descuento familia'],
  },
  {
    id: '3',
    clienteNombre: 'Diego',
    clienteApellidos: 'Sánchez Ruiz',
    telefono: '+34 612 987 654',
    servicio: 'Corte + Barba',
    variante: 'Estilo moderno',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-01-23',
    horaInicio: '12:30',
    descuentos: ['Pack completo'],
  },
  {
    id: '4',
    clienteNombre: 'Alex',
    clienteApellidos: 'González Torres',
    telefono: '+34 634 567 890',
    servicio: 'Corte infantil',
    variante: 'Primera vez',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-01-23',
    horaInicio: '14:00',
    descuentos: ['Promo niños'],
  },
  {
    id: '5',
    clienteNombre: 'Roberto',
    clienteApellidos: 'Morales Vila',
    telefono: '+34 645 234 567',
    servicio: 'Tratamiento capilar',
    variante: 'Anti-caspa',
    sucursal: 'Parets',
    profesional: 'Sara López',
    fechaISO: '2025-01-23',
    horaInicio: '15:30',
  },
  {
    id: '6',
    clienteNombre: 'Fernando',
    clienteApellidos: 'Castro Vega',
    telefono: '+34 623 456 789',
    servicio: 'Arreglo de barba',
    variante: 'Perfilado completo',
    sucursal: 'Lliçà',
    profesional: 'Carlos Rodríguez',
    fechaISO: '2025-01-23',
    horaInicio: '16:00',
    descuentos: ['Cliente frecuente'],
  },
  {
    id: '7',
    clienteNombre: 'Andrés',
    clienteApellidos: 'Ramírez Ortiz',
    telefono: '+34 656 789 012',
    servicio: 'Corte clásico',
    variante: 'Tijera únicamente',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-01-23',
    horaInicio: '17:00',
  },
  {
    id: '8',
    clienteNombre: 'Miguel',
    clienteApellidos: 'Herrera Díaz',
    telefono: '+34 667 890 123',
    servicio: 'Lavado + Peinado',
    variante: 'Para evento',
    sucursal: 'Lliçà',
    profesional: 'Ana Jiménez',
    fechaISO: '2025-01-23',
    horaInicio: '18:30',
    descuentos: ['Oferta especial'],
  },
  {
    id: '9',
    clienteNombre: 'Carlos',
    clienteApellidos: 'Mendoza Silva',
    telefono: '+34 678 901 234',
    servicio: 'Corte de cabello adulto',
    variante: 'Con líneas',
    sucursal: 'Parets',
    profesional: 'Luis Martínez',
    fechaISO: '2025-01-23',
    horaInicio: '09:00',
    descuentos: ['Primera visita'],
    noShow: true,
  },
];
